import './globals.css'
import { telegraf, poppins } from './fonts'
import { ToastProvider } from '../components/ui/Base/toast-provider'
import { ToastContainer } from '../components/ui/Base/Toast'
import { useToast } from '../hooks/use-toast'


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${telegraf.variable} ${poppins.variable} antialiased`}>
        {children}
        <ToastProvider />
      </body>
    </html>
  )
}